export const Colors = {
  // PRIMARY COLORS
  PRIMARY_MAIN: "#FF6A00",
  PRIMARY_HOVER: "#FF8A00",
  PRIMARY_PRESSED: "#FF5C00",
  PRIMARY_SECONDARY: "#F4F5F7",

  // SUCCESS COLORS
  SUCCESS_MAIN: "#1FCC79",
  SUCCESS_SECONDARY: "#E3FFF8",
  
  // INFO COLORS
  INFO_MAIN: "#2E3E5C",
  INFO_SECONDARY: "#9FA5C0",

  // GRAYSCALE COLORS
  GRAY_BORDER: "#E0E0E0",
};
